server {
        listen       80;
        server_name  yourdomain;

      #允许跨域请求的域，* 代表所有
     # add_header 'Access-Control-Allow-Origin' '*';
      #允许带上cookie请求
     # add_header 'Access-Control-Allow-Credentials' 'true';
      #允许请求的方法，比如 GET/POST/PUT/DELETE
     # add_header 'Access-Control-Allow-Methods' '*';
      #允许请求的header
     # add_header 'Access-Control-Allow-Headers' '*' ;


    add_header 'Access-Control-Allow-Origin' $http_origin;
    #add_header 'Access-Control-Allow-Origin' 'yourdomain';
    add_header 'Access-Control-Allow-Credentials' 'true';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS'; # 添加允许的请求方法
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,xy-ds-log-seq'; # 添加允许的请求头
    add_header 'Access-Control-Max-Age' 1728000; # 预检请求的有效期 (20天)

    if ($request_method = 'OPTIONS') {
 #       add_header 'Content-Type' 'text/plain; charset=utf-8';
  #      add_header 'Content-Length' 0;
        return 204;
    }
        
        location /scratch/ {
            access_by_lua_file lualib/tof_auth.lua;
            alias /data/service/scratch-gui/build/;
            try_files $uri $uri/ /scratch/index.html;
            
            # 添加适当的 MIME 类型
            types {
                application/javascript js;
                text/css css;
                text/html html;
                image/svg+xml svg;
                image/png png;
                image/gif gif;
            }
        }

        # 处理不带斜杠的 /scratch 路径，重定向到带斜杠的版本
        location = /scratch {
            return 301 /scratch/;
        }
}